import type { Metadata } from 'next';
import './globals.css';

import { Gruppo, Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const gruppo = Gruppo({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400'],
  style: 'normal',
  variable: '--font-gruppo',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gruppo.variable} ${inter.variable}`}>{children}</body>
    </html>
  );
}
